In [1]:
import pandas as pd
import numpy as np

In [9]:
qb = pd.read_csv("QB_COA_SEM-IV_2023 (1).csv")

In [10]:
qb.head()

,"L.J Institute of Engineering and Technology, Ahmedabad. (COA) Question Bank (SEM-IV )",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Note : This question bank is only for referenc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chapt er_nu mber,grou p_id,question_text,answer_text,ma rks,option1,option2,option3,option4,option5,option6
2,1,1,What is computer architecture?,b,1,set of categories and methods that specify the...,set of principles and methods that specify the...,set of functions and methods that specify the ...,None of the mentioned,NaN,NaN
3,1,2,What is computer organization?,a,1,structure and behaviour of a computer system a...,structure of a computer system as observed by ...,structure and behaviour of a computer system a...,All of the mentioned,NaN,NaN
4,1,3,Represent fix point representation for Unsigne...,"0110.110,(6.75)10",1,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# qb.drop("Unnamed: 1",axis=1,inplace=True)
qb.reset_index(col_level=1)
# qb.rename(columns={ "L.J Institute of Engineering and Technology, Ahmedabad. (COA) Question Bank (SEM-IV )":"ch_no","Unnamed: 2":"que","Unnamed: 3":"ans","Unnamed: 5":"opt1","Unnamed: 6":"opt2","Unnamed: 7":"opt3","Unnamed: 8":"opt4"},inplace=True)
qb.head()

,"L.J Institute of Engineering and Technology, Ahmedabad. (COA) Question Bank (SEM-IV )",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Note : This question bank is only for referenc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chapt er_nu mber,grou p_id,question_text,answer_text,ma rks,option1,option2,option3,option4,option5,option6
2,1,1,What is computer architecture?,b,1,set of categories and methods that specify the...,set of principles and methods that specify the...,set of functions and methods that specify the ...,None of the mentioned,NaN,NaN
3,1,2,What is computer organization?,a,1,structure and behaviour of a computer system a...,structure of a computer system as observed by ...,structure and behaviour of a computer system a...,All of the mentioned,NaN,NaN
4,1,3,Represent fix point representation for Unsigne...,"0110.110,(6.75)10",1,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# qb.loc[(qb["ch_no"]=="1") & (qb["opt1"].notna())]
qb["ch_no"].loc[qb["ch_no"]=="1"]

2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
30    1
31    1
32    1
33    1
34    1
35    1
39    1
40    1
41    1
42    1
Name: ch_no, dtype: object

In [93]:
# qb.loc[qb["opt1"].notna()]